# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f301298abbb0d08b7a8ca1caf28dda71226d3b19573f1f9a75a0dd228eba6e4632685e4d8cda50267c83c9199b27b1e9ffd4c8aa6cd5b0d0c7c8b7186deed870

test:
  secret_key_base: d31c178e2dc6cafa17cc345600c2cda6bfa8558ffec9217113cce10bf0f666f454fd810b38c7510f0077e30dfc100c8ac96b7691b1e89b26d06bd1b9e00ce843

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
